spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:7080/realms/master"
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

server:
  port: 8072
  error:
    include-message: always
    include-stacktrace: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10

logging:
  level:
    org.springframework.security: debug
    org.springframework.security.oauth2: DEBUG