spring:
  application:
    name: orders
  config:
    import: configserver:http://localhost:8888

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    stream:
      bindings:
        sendCommunication-out-0:
          destination: send-communication
          group: ${spring.application.name}
        orderConfirmation-in-0:
          destination: confirmation-sent
      kafka:
        binder:
          brokers:
            - localhost:9092

# rabbitmq:
#   host: localhost
#   port: 5672
#   username: guest
#   password: guest
#   connection-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8090

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5

  ratelimiter:
    configs:
      default:
        timeout-duration: 1000
        limit-refresh-period: 5000
        limit-for-period: 2